apiVersion: v1
kind: Secret
metadata:
  name: db2app-secret
  namespace: pipelines-tutorial
stringData:
  ghettoes1Node04_db2_password: db2inst1_ZZ
  ghettoes1Node04_db2_user: db2inst1_ZZ
type: Opaque
